export const signUpConfig = {
  hideAllDefaults: true,
  defaultCountryCode: "33",
  signUpFields: [
    {
      label: "Full name",
      key: "name",
      required: true,
      displayOrder: 1,
      type: "string",
    },
    {
      label: "Email",
      key: "email",
      required: true,
      displayOrder: 2,
      type: "string",
    },
    {
      label: "Phone Number",
      key: "phone_number",
      required: true,
      displayOrder: 3,
      type: "string",
    },
    {
      label: "Username",
      key: "preferred_username",
      required: true,
      displayOrder: 4,
      type: "string",
    },
    {
      label: "Password",
      key: "password",
      required: true,
      displayOrder: 5,
      type: "password",
    },
    {
      label: "Birthdate",
      key: "birthdate",
      required: true,
      displayOrder: 6,
      type: "default",
    },
    {
      label: "Address",
      key: "address",
      required: true,
      displayOrder: 7,
      type: "default",
    },
  ],
};
